/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
#include <iostream>
/* Header for class net_orbyfied_j8_math_expr_vm_StackExpressionNativeVM */

#ifndef _Included_net_orbyfied_j8_math_expr_vm_StackExpressionNativeVM
#define _Included_net_orbyfied_j8_math_expr_vm_StackExpressionNativeVM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_orbyfied_j8_math_expr_vm_StackExpressionNativeVM
 * Method:    execute0
 * Signature: (Lnet/orbyfied/j8/math/expr/vm/ExecutionEnvironment;[B)V
 */
JNIEXPORT void JNICALL Java_net_orbyfied_j8_math_expr_vm_StackExpressionNativeVM_execute0
  (JNIEnv *, jobject, jobject, jbyteArray) {
    std::cout << "Hello World!" << std::endl;
}

#ifdef __cplusplus
}
#endif
#endif
